language: c

os: linux
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update
  - sudo sudo apt-get install -y gawk git wget diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping mercurial autoconf automake groff curl lzop asciidoc u-boot-tools sshpass ssh-askpass zip xz-utils kpartx

script:
  - mkdir -p ~/bin
  - curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo

  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

  - PATH=${PATH}:~/bin
  - mkdir xore_yocto
  - cd xore_yocto
  - echo -e "y\n" | repo init -u https://github.com/TechNexion/tn-imx-yocto-manifest.git -b sumo_4.14.y_GA-next -m imx-4.14.98-2.0.1_patch.xml
  - repo sync -j8

  - EULA="1" DISTRO=fsl-imx-xwayland MACHINE=xore-imx8mm source edm-setup-release.sh -b build-xwayland-xore-imx8mm
  - bitbake core-image-minimal
